# Generated by Django 3.1.3 on 2020-11-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('shop_no', models.CharField(max_length=80, verbose_name='商品编码')),
                ('shop_name', models.FileField(max_length=80, upload_to='', verbose_name='商品名称')),
                ('shop_num', models.IntegerField(default=0, verbose_name='商品数量')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
    ]
