# Generated by Django 3.2.5 on 2021-09-25 08:47

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('commodity_no', models.CharField(max_length=80, unique=True, verbose_name='商品编码')),
                ('commodity_name', models.CharField(max_length=80, unique=True, verbose_name='商品名称')),
                ('included_products', jsonfield.fields.JSONField(default=dict)),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('order_no', models.IntegerField(default=100, verbose_name='排列顺序')),
            ],
            options={
                'verbose_name': '淘宝商品',
                'verbose_name_plural': '淘宝商品',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('product_no', models.CharField(max_length=80, null=True, verbose_name='商品规格编码')),
                ('product_name', models.CharField(max_length=80, verbose_name='商品规格')),
                ('included_shops', jsonfield.fields.JSONField(default=dict)),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('order_no', models.IntegerField(default=100, verbose_name='排列顺序')),
            ],
            options={
                'verbose_name': '淘宝SKU',
                'verbose_name_plural': '淘宝SKU',
            },
        ),
        migrations.CreateModel(
            name='SaleRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('commodity_no', models.CharField(max_length=80, verbose_name='商品编码')),
                ('commodity_name', models.CharField(max_length=80, verbose_name='商品名称')),
                ('product_no', models.CharField(max_length=80, verbose_name='商品规格编码')),
                ('product_name', models.CharField(max_length=80, verbose_name='规格名称')),
                ('saled_num', models.IntegerField(default=0, verbose_name='销售数量')),
                ('remark', models.TextField(null=True, verbose_name='备注')),
                ('saled_shops', jsonfield.fields.JSONField(default=dict)),
                ('sign', models.CharField(max_length=30, null=True, verbose_name='时间戳标识')),
            ],
            options={
                'verbose_name': '销售记录',
                'verbose_name_plural': '销售记录',
            },
        ),
        migrations.CreateModel(
            name='SendOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=30, verbose_name='领取人')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='领取时间')),
                ('status', models.CharField(choices=[('Done', '已结清'), ('Process', '未结清')], default='Process', max_length=10)),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '领取商品',
                'verbose_name_plural': '领取商品',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('shop_no', models.CharField(max_length=80, unique=True, verbose_name='货物编号')),
                ('shop_name', models.CharField(max_length=80, unique=True, verbose_name='货物名称')),
                ('shop_num', models.IntegerField(default=0, verbose_name='货物数量')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('order_no', models.IntegerField(default=100, verbose_name='排列顺序')),
            ],
            options={
                'verbose_name': '货物',
                'verbose_name_plural': '货物',
            },
        ),
        migrations.CreateModel(
            name='ShopRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('shop_no', models.CharField(max_length=80, verbose_name='货品编号')),
                ('shop_name', models.CharField(max_length=80, verbose_name='货品名称')),
                ('change_num', models.IntegerField(verbose_name='变化数量')),
                ('option', models.CharField(choices=[('Sale', '卖出'), ('Inrepo', '直接入库')], default='Inrepo', max_length=10)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='日期')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('sign', models.CharField(max_length=30, null=True, verbose_name='时间戳标识')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShopOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='预定日期')),
                ('num', models.IntegerField(default=0, verbose_name='预定数量')),
                ('status', models.CharField(choices=[('Done', '已结清'), ('Process', '未结清')], default='Process', max_length=10)),
                ('material', models.CharField(max_length=100, null=True, verbose_name='材料')),
                ('in_num', models.IntegerField(default=0, verbose_name='已归还数量')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='repo.shop')),
            ],
            options={
                'verbose_name': '配件预定',
                'verbose_name_plural': '配件预定',
            },
        ),
        migrations.CreateModel(
            name='SendRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('change_num', models.IntegerField(default=0, verbose_name='归还数量')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='归还日期')),
                ('remark', models.TextField(null=True, verbose_name='备注')),
                ('send', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='repo.sendout')),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='repo.shop')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SendOutShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('out_num', models.IntegerField(default=0, verbose_name='领取数量')),
                ('in_num', models.IntegerField(default=0, verbose_name='归还数量')),
                ('option', models.CharField(choices=[('Bring', '拿走'), ('Back', '归还')], default='Bring', max_length=10)),
                ('send', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repo.sendout')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repo.shop')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sendout',
            name='sendoutshops',
            field=models.ManyToManyField(through='repo.SendOutShop', to='repo.Shop'),
        ),
        migrations.CreateModel(
            name='ProductRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('product_no', models.CharField(max_length=80, verbose_name='商品编码')),
                ('product_name', models.CharField(max_length=80, verbose_name='商品名称')),
                ('change_num', models.IntegerField(verbose_name='变化数量')),
                ('option', models.CharField(choices=[('Sale', '卖出'), ('Pakage', '装货'), ('Inrepo', '入库')], default='Pakage', max_length=10)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='日期')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='repo.sendout', verbose_name='配送')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('num', models.IntegerField(verbose_name='送回数量')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='送回时间')),
                ('remark', models.TextField(null=True, verbose_name='备注')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repo.shoporder')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
