# Generated by Django 3.1.3 on 2020-11-24 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('repo', '0002_auto_20201120_0720'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepoIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('shop_num', models.IntegerField(default=0, verbose_name='商品数量')),
                ('is_custom', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repo.shop', verbose_name='卡片类型')),
            ],
            options={
                'verbose_name': '入库',
                'verbose_name_plural': '入库',
            },
        ),
    ]
