# Generated by Django 3.2.5 on 2021-10-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0002_shoprecord_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='threshold',
            field=models.IntegerField(blank=True, default=0, verbose_name='阀值'),
        ),
    ]
