# Generated by Django 3.1.3 on 2020-11-24 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0003_repoin'),
    ]

    operations = [
        migrations.AddField(
            model_name='repoin',
            name='in_time',
            field=models.DateField(default=datetime.date(2020, 11, 24)),
        ),
    ]
