# Generated by Django 3.2.9 on 2021-11-09 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0003_shop_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='total_num',
            field=models.IntegerField(default=0, verbose_name='货品总量'),
        ),
    ]
