# Generated by Django 3.1.3 on 2020-11-25 07:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0004_repoin_in_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repoin',
            name='in_time',
            field=models.DateField(default=datetime.date(2020, 11, 25), verbose_name='入库时间'),
        ),
        migrations.AlterField(
            model_name='repoin',
            name='is_custom',
            field=models.BooleanField(default=False, verbose_name='是否定制'),
        ),
    ]
