# Generated by Django 3.1.3 on 2020-12-01 14:02

import datetime
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0005_auto_20201125_0745'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=30, verbose_name='领取人')),
                ('date', models.DateField(default=datetime.date(2020, 12, 1), verbose_name='领取时间')),
                ('take', jsonfield.fields.JSONField(default=dict)),
                ('status', jsonfield.fields.JSONField(choices=[('Done', '已结清'), ('Process', '未结清')], default=dict, max_length=10)),
                ('backup', models.TextField(verbose_name='备注')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='repoin',
            name='in_time',
            field=models.DateField(default=datetime.date(2020, 12, 1), verbose_name='入库时间'),
        ),
        migrations.AlterField(
            model_name='repoin',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repo.shop', verbose_name='产品'),
        ),
        migrations.CreateModel(
            name='SendIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=30, verbose_name='归还人')),
                ('date', models.DateField(default=datetime.date(2020, 12, 1), verbose_name='归还时间')),
                ('bring', jsonfield.fields.JSONField(default=dict)),
                ('backup', models.TextField(verbose_name='备注')),
                ('sendout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repo.sendout', verbose_name='对应领取批次')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
