# Generated by Django 3.1.3 on 2020-12-01 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0006_auto_20201201_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repoin',
            name='in_time',
            field=models.DateField(default=datetime.date.today, verbose_name='入库时间'),
        ),
        migrations.AlterField(
            model_name='sendin',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='归还时间'),
        ),
        migrations.AlterField(
            model_name='sendout',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='领取时间'),
        ),
    ]
