# Generated by Django 3.1.3 on 2020-12-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0007_auto_20201201_1407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sendin',
            options={'verbose_name': '归还商品', 'verbose_name_plural': '归还商品'},
        ),
        migrations.AlterModelOptions(
            name='sendout',
            options={'verbose_name': '领取商品', 'verbose_name_plural': '领取商品'},
        ),
        migrations.AlterField(
            model_name='sendout',
            name='status',
            field=models.CharField(choices=[('Done', '已结清'), ('Process', '未结清')], max_length=10),
        ),
    ]
