# Generated by Django 3.1.3 on 2020-12-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0009_auto_20201201_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendin',
            name='backup',
            field=models.TextField(blank=True, default='', verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='sendout',
            name='backup',
            field=models.TextField(blank=True, default='', verbose_name='备注'),
        ),
    ]
