# Generated by Django 3.1.3 on 2020-12-07 16:54

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0010_auto_20201202_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendout',
            name='bring',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
