# Generated by Django 3.1.3 on 2021-01-03 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0011_sendout_bring'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('order_date', models.DateField(default=datetime.date.today, verbose_name='预定日期')),
                ('name', models.CharField(max_length=80, verbose_name='商品名称')),
                ('num', models.IntegerField(default=0, verbose_name='预定数量')),
                ('material', models.CharField(max_length=100, verbose_name='材料')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
            ],
            options={
                'verbose_name': '商品预定',
                'verbose_name_plural': '商品预定',
            },
        ),
        migrations.DeleteModel(
            name='SendIn',
        ),
    ]
