# Generated by Django 3.1.3 on 2021-01-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0012_auto_20210103_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoporder',
            name='status',
            field=models.CharField(choices=[('Done', '已结清'), ('Process', '未结清')], default='Process', max_length=10),
        ),
        migrations.AlterField(
            model_name='sendout',
            name='status',
            field=models.CharField(choices=[('Done', '已结清'), ('Process', '未结清')], default='Process', max_length=10),
        ),
    ]
