# Generated by Django 3.1.3 on 2021-01-09 12:11

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0013_auto_20210109_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoporder',
            name='bring',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shoporder',
            name='in_num',
            field=models.IntegerField(default=0, verbose_name='归还数量'),
        ),
    ]
