# Generated by Django 3.1.3 on 2021-01-12 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0014_auto_20210109_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('product_no', models.CharField(max_length=80, unique=True, verbose_name='商品编码')),
                ('product_name', models.CharField(max_length=80, verbose_name='商品名称')),
                ('product_num', models.IntegerField(default=0, verbose_name='商品数量')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
        migrations.AlterField(
            model_name='repoin',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repo.shop', verbose_name='配件'),
        ),
        migrations.AlterField(
            model_name='repoin',
            name='shop_num',
            field=models.IntegerField(default=0, verbose_name='配件数量'),
        ),
    ]
