# Generated by Django 3.1.3 on 2021-03-04 07:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0017_auto_20210114_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='product',
            name='remark',
            field=models.TextField(blank=True, default='', verbose_name='备注'),
        ),
    ]
