# Generated by Django 3.1.3 on 2021-03-04 10:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0018_auto_20210304_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrecord',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='时间'),
        ),
        migrations.AddField(
            model_name='productrecord',
            name='remark',
            field=models.TextField(blank=True, default='', verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='productrecord',
            name='option',
            field=models.CharField(choices=[('Sale', '卖出'), ('Pakage', '装货'), ('Inrepo', '入库')], default='Pakage', max_length=10),
        ),
    ]
