# Generated by Django 3.1.3 on 2021-03-06 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0019_auto_20210304_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrecord',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
    ]
