# Generated by Django 3.1.3 on 2021-03-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0020_auto_20210306_0408'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order_no',
            field=models.IntegerField(default=100, verbose_name='排列顺序'),
        ),
    ]
