# Generated by Django 3.1.3 on 2021-03-09 02:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0021_product_order_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('part_name', models.CharField(max_length=80, verbose_name='配件名称')),
                ('part_num', models.IntegerField(default=0, verbose_name='配件数量')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='创建日期')),
                ('order_no', models.IntegerField(default=100, verbose_name='排列顺序')),
            ],
            options={
                'verbose_name': '配件',
                'verbose_name_plural': '配件',
            },
        ),
        migrations.CreateModel(
            name='PartRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('part_name', models.CharField(max_length=80, verbose_name='配件名称')),
                ('change_num', models.IntegerField(verbose_name='变化数量')),
                ('option', models.CharField(choices=[('Sale', '卖出'), ('Order', '订购')], default='Order', max_length=10)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='日期')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='productrecord',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='日期'),
        ),
    ]
